pipeline:
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER##mu-}/mu-${CI_REPO_NAME}"
      tags: latest
    secrets: [docker_username, docker_password]
    when:
      event: push
      branch: [master, main]
